// Generated by CoffeeScript 1.11.1
(function() {
  SEE.Profiler = (function() {
    function Profiler(name) {
      this.name_string = name;
      this.overall_time = 0;
      this.num_logs = 0;
      this.min_time = Number.MAX_VALUE;
      this.max_time = Number.MIN_VALUE;
    }

    Profiler.prototype.logTime = function(time) {
      this.num_logs += 1;
      this.overall_time += time;
      this.min_time = Math.min(this.min_time, time);
      return this.max_time = Math.max(this.max_time, time);
    };

    Profiler.prototype.toString = function() {
      return this.name_string + "time log: (average: " + this.overall_time / this.num_logs + ", min: " + this.min_time + ", max: " + this.max_time + ") milliseconds.";
    };

    return Profiler;

  })();

}).call(this);
