// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  SEE.I_Keyboard_Main = (function(superClass) {
    extend(I_Keyboard_Main, superClass);

    function I_Keyboard_Main(scene, camera) {
      this.scene = scene;
      this.camera = camera;
      I_Keyboard_Main.__super__.constructor.call(this);
      this.state = "idle";
      this.add_universal_controller(new SEE.I_Seeing_Mode(this.scene, this.camera));
    }

    return I_Keyboard_Main;

  })(BDS.Controller_Group);

}).call(this);
