// Generated by CoffeeScript 1.11.1

/*

Cube Rotation Controller.

Written by Bryce Summmers on 6 - 6 - 2017.

 - A Test time controller that takes every cube in the scene and rotates it by a fixed amount.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  SEE.I_Rotate_Cubes = (function(superClass) {
    extend(I_Rotate_Cubes, superClass);

    function I_Rotate_Cubes(scene, camera) {
      this.scene = scene;
      this.camera = camera;
      I_Rotate_Cubes.__super__.constructor.call(this);
      this.time_count = 0.0;
      this.time_step = 2000.0;
    }

    I_Rotate_Cubes.prototype.time = function(dt) {
      var cube, cubes, i, len;
      cubes = this.scene.getObjects();
      for (i = 0, len = cubes.length; i < len; i++) {
        cube = cubes[i];
        cube.rotation.x += dt * .001;
        cube.rotation.y += dt * .001;
      }
    };

    return I_Rotate_Cubes;

  })(BDS.Interface_Controller_Time);

}).call(this);
